### ISSUE TITLE
Improve logs usability

### ISSUE THREAD

**Issue by alexey-nbl** [EatonGMBD/imp-central-impt#14]
Suggested by @deldrid1 in https://github.com/EatonGMBD/imp-central-impt/pull/13#pullrequestreview-359113531

- If only one device ID is included in the list of arguments, do not log the device ID with every log.

- Add a CLI flag to eliminate timestamps, compress them to HH:MM:SS.XXXX, or print delta time between logs?
  - Not sure what is used under the hood here, but passing in a [Moment format string](https://momentjs.com/docs/#/displaying/format/) could be an option?
  - I'm happy to talk about different options, ease of implementation, etc. here to land on what the easiest thing is

**Comment by alexey-nbl** [comment]
@deldrid1 
 
A proposal:

Add a non-mandatory value to the currently existing `--log` option:
  "full" (default when the value is not specified) - the current default log output (exactly what is returned by impCentral REST API).
  "no-ts" - eliminates timestamps
  "min-ts" - timestamp in the minimal format ("HH:MM:SS.XXX")
  "delta-ts" - delta time between log records ("+[HH:][MM:]SS.XXX")
  "custom-ts=<custom_ts_format>" - defines a custom format for timestamps (eg. "YYYY/MM/DD HH:mm:ss") - will not be supported now but theoretically feasible in future.

The `--log` option to be updated in:
  `impt build run`
  `impt device restart`
  `impt dg restart`
The `--log` option to be added (as a non-mandatory option) to:
  `impt log stream`
  `impt log get`

Default behavior will be kept as now.

Need to agree which timestamp output formats (`--log` values) to support now.
Austin, what is your opinion?

**Comment by deldrid1** [comment]
I think this is a fine proposal.  My priority is to support `full`, `no-ts`, and `delta-ts` but if `min-ts` is simple enough to add we can include it as well.  I agree that we don't need to bother with `custom-ts` for now as it probably adds a lot of complexity around testing for very little value.  One other option that comes to mind as a nice to have is `epoch-ts` which would be seconds or milliseconds since the Jan 1 1970 epoch and could be useful potentially?

The one outstanding issue is **If only one device ID is included in the list of arguments, do not log the device ID with every log.**  I would like to see this retained in the scope and change the behavior of `imp log ...` specifically.

**Comment by alexey-nbl** [comment]
Will support `full`, `no-ts`, `delta-ts`, `min-ts` and `epoch-ts` - should not be a problem.

Yes, the first request is in the scope.
If there is only one device, then deviceId will not be displayed.
It will affect all log-related commands, in the "default" and "minimal" output mode.

**Comment by mm-gmbd** [comment]
Fixed with #20
